name: sili

services:
  sili-core:
    container_name: sili-core
    build:
      context: .
      dockerfile: ./docker/sili-core.dockerfile
    restart: always
    networks:
      sili-network:
        aliases:
          - core.sili.local
    # ports:
    #   - '3100:3100'
    volumes:
      - ./public:/data/public
      # 主要的 Node.js 项目文件
      - ./src/:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./.npmrc:/app/.npmrc
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./.env:/app/.env
      # koishi自带的data文件夹
      - ./data/core:/app/data
      # 缓存文件夹
      - /root/.cache/puppeteer
    depends_on:
      - mongo

  caddy:
    image: caddy:2.9-alpine
    container_name: sili-caddy
    restart: always
    networks:
      sili-network:
        aliases:
          - caddy.sili.local
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./public:/data/public

  mongo:
    image: mongo:8.0-noble
    container_name: sili-mongo
    networks:
      sili-network:
        aliases:
          - mongo.sili.local
    restart: always
    ports:
      # 我们暴露此端口到宿主机，这样就能通过 MongoDB Compase 等应用连接它
      - '27017:27017'
    # 暂时不设密码，注意配置防火墙，不能将此端口暴露到公网
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
    #   MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./public:/data/public

  llonebot:
    container_name: sili-llonebot
    image: initialencounter/llonebot:latest
    environment:
      VNC_PASSWD: ${VNC_PASSWD}
    privileged: true
    restart: always
    ports:
      - '6788:7081' # VNC
    volumes:
      - ./data/private/LiteLoader:/LiteLoader/data
      - qqnt_data:/data/.config/QQ
    networks:
      sili-network:
        aliases:
          - llonebot.sili.local

  redis:
    container_name: sili-redis
    image: redis/redis-stack:latest
    restart: always
    networks:
      sili-network:
        aliases:
          - redis.sili.local
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./data/private/qdrant_storage:/qdrant/storage

  mem0:
    container_name: sili-mem0
    build:
      context: ./docker/mem0
      dockerfile: Dockerfile
    restart: always
    networks:
      sili-network:
        aliases:
          - mem0.sili.local
    volumes:
      - ./docker/mem0/app.py:/app/app.py
      - ./.env:/app/.env
    ports:
      - '5000:5000'
    environment:
      REDIS_URL: 'redis://redis.sili.local:6379'
    depends_on:
      - redis

networks:
  sili-network:
    name: sili-network

volumes:
  mongo_data:
    name: sili_mongo_data
  qqnt_data:
    name: sili_qqnt_data
